package gg.rsmod.plugins.content.skills.prayer.burying

import gg.rsmod.plugins.api.cfg.Items

// superior req 70 to bury
enum class BoneBury(val item: Int, val xpGained: Double, val levelToBury: Int = 1) {
    BONES(Items.BONES, 4.5),
    BIG_BONES(Items.BIG_BONES, 15.0),
    DRAGON_BONES(Items.DRAGON_BONES, 72.0),
    WOLF_BONES(Items.WOLF_BONES, 4.5),
    BURNT_BONES(Items.BURNT_BONES, 4.5),
    MONKEY_BONES(Items.MONKEY_BONES, 5.0),
    BAT_BONES(Items.BAT_BONES, 5.3),
    JOGRE_BONES(Items.JOGRE_BONES, 15.0),
    ZOGRE_BONES(Items.ZOGRE_BONES, 22.5),
    SHAIKAHAN_BONES(Items.SHAIKAHAN_BONES, 25.0),
    BABYDRAGON_BONES(Items.BABYDRAGON_BONES, 30.0),
    WYRM_BONES(Items.WYRM_BONES, 50.0),
    WYVERN_BONES(Items.WYVERN_BONES, 72.0),
    DRAKE_BONES(Items.DRAKE_BONES, 80.0),
    FAYRG_BONES(Items.FAYRG_BONES, 84.0),
    LAVA_DRAGON_BONES(Items.LAVA_DRAGON_BONES, 85.0),
    RAURG_BONES(Items.RAURG_BONES, 96.0),
    HYDRA_BONES(Items.HYDRA_BONES, 110.0),
    DAGANNOTH_BONES(Items.DAGANNOTH_BONES, 125.0),
    OURG_BONES(Items.OURG_BONES, 140.0),
    SUPERIOR_DRAGON_BONES(Items.SUPERIOR_DRAGON_BONES, 150.0, 70),
    BONES_APE_ATOLL(Items.BONES_3187, 3.0),
    SMALL_ZOMBIE_MONKEY_BONES(Items.MONKEY_BONES_3185, 5.0),
    LARGE_ZOMBIE_MONKEY_BONES(Items.MONKEY_BONES_3186, 5.0),
    GORILLA_BONES(Items.MONKEY_BONES_3181, 18.0),
    BEARDED_GORILLA_BONES(Items.MONKEY_BONES_3182, 18.0),
}